name: risk-pmml-builder
channels:
  - conda-forge
dependencies:
  - jupyter
  - keras
  - matplotlib
  - numpy>=1.16.0
  - pandas
  - scikit-learn
  - tensorflow
  - pip
  - pip:
      - nyoka
      - keras2pmml